<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="smita-PC2" name="My test cases" tests="17" failures="2" timestamp="12 Nov 2014 08:15:28 GMT" time="0.063" errors="0">
  <testcase name="Case1" time="0.016" classname="package01.Test01">
    <failure type="java.lang.AssertionError" message="expected [y] but found [x]">
      <![CDATA[java.lang.AssertionError: expected [y] but found [x]
	at package01.Test01.Case1(Test01.java:30)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Case1 -->
  <testcase name="Case2" time="0.0" classname="package01.Test01"/>
  <testcase name="Case1" time="0.0" classname="package01.Test02"/>
  <testcase name="Case2" time="0.0" classname="package01.Test02"/>
  <testcase name="Case3" time="0.0" classname="package01.Test02"/>
  <testcase name="Case1" time="0.0" classname="package02.Test03"/>
  <testcase name="Case2" time="0.0" classname="package02.Test03"/>
  <testcase name="Case3" time="0.0" classname="package02.Test03"/>
  <testcase name="Case4" time="0.0" classname="package02.Test03"/>
  <testcase name="Case5" time="0.0" classname="package02.Test03"/>
  <testcase name="Case1" time="0.0" classname="package03.Test04"/>
  <testcase name="Case2" time="0.0" classname="package03.Test04"/>
  <testcase name="Case1" time="0.0" classname="package03.Test05"/>
  <testcase name="Case2" time="0.0" classname="package03.Test05">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
	at package03.Test05.Case2(Test05.java:19)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Case2 -->
  <testcase name="Case3" time="0.0" classname="package03.Test05"/>
  <testcase name="Case4" time="0.0" classname="package03.Test05"/>
  <testcase name="Case5" time="0.0" classname="package03.Test05"/>
</testsuite> <!-- My test cases -->
